apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: demo-blog
data:
  BLOG_TITLE: "Le Blog de Iva Toshkova"
  BLOG_SUBTITLE: "Mes aventures GitOps"
  AUTHOR: "iva"
  VERSION: "1.0.0"
  THEME: "dark"